#!/usr/bin/perl
# -*-Shell-script-*-
#
# functions     This file contains functions to be used by most or all
#               shell scripts in the /usr/local/bin.
#		This is TOPS team super functions. If you need use it, Please
#		contact juehai.gy@taobao.com.

PID=$$

PATH="/sbin:/usr/sbin:/bin:/usr/bin"
export PATH

function __readlink() {
    ls -bl "$@" 2>/dev/null| awk '{ print $NF }'
}

function shell_lock(){
	[ -z $LOCK ] && LOCK=$1
	[ -z $LOCK ] && echo "You need set LOCK env.." && exit 1
	locked_pid=$(__readlink $LOCK)
	if [ $locked_pid ]
	then
		echo "Found lock.. pid: "$locked_pid
		process=$(ps -p $locked_pid)
		if [ $? != 0 ]
		then
			echo "Invalid lock.. Cover it.."
			ln -sf $PID $LOCK
		else
			if [ $PID == $locked_pid ]
			then
				echo "In my lock... go on."
			else
				echo "Other Process is blocking me, exit..."
				echo $process
				exit 0
			fi
		fi
	else
		echo "Not found lock.."
		ln -sf $PID $LOCK
	fi
}
function shell_unlock(){
	[ ! -z $LOCK ] || LOCK=$1
	locked_pid=$(__readlink $LOCK)
	if [ $locked_pid == $PID ]
	then
		rm -f $LOCK
		echo "unlocked .."
	else
		echo "$PID is in running.."
		exit 1
	fi
}
