#!/usr/bin/perl
#!/usr/local/bin/perl -w

use strict;
use Cwd;

my $dir = $ARGV[0];

die "Directory not provided" unless defined($dir);
die "Directory doesn't exist" unless -d $dir;
die "$dir/.manifest.md5sum not found" unless -f "$dir/.manifest.md5sum";

open my $file, "$dir/.manifest.md5sum";
while (<$file>) {
    my ($sum, $fname) = split /\s+/;
    unless(-f "$dir/$fname") {
        close($file);
        die "$dir/$fname does not exist";
    }
}
close $file;

verify_all_manifests($dir);

sub verify_all_manifests {
    my $dir = shift;
    if (-f "$dir/.manifest.md5sum" and -s "$dir/.manifest.md5sum") {
	my $cur_dir = getcwd();
        chdir($dir);
        system("md5sum -c .manifest.md5sum");
        die "$dir/.manifest.md5sum failed verification" if($? >> 8);
	chdir($cur_dir);
    }            

    my $d;
    opendir $d, $dir;
    my @dirs = grep { $_ !~ /^\./ && -d "$dir/$_" } readdir $d;
    closedir $d;

    verify_all_manifests("$dir/$_") for(@dirs);
}



